[project]
name = "cpp_notes"
version = "1.0.0"

[paths]
output_dir = "output"
compile_commands = "code/cmake-build-debug/compile_commands.json"

[pages]
homepage = "notes/index.md"
paths = [
    "notes/lectures/лекция 14.09.md",
    "notes/lectures/лекция 16.09.md",
    "notes/lectures/лекция 21.09.md",
    "notes/lectures/лекция 23.09.md",
    "notes/lectures/лекция 27.09.md",
    "notes/lectures/лекция 30.09.md",
    "notes/lectures/лекция 05.10.md",
    "notes/lectures/лекция 07.10.md",
    "notes/lectures/лекция 12.10.md",
    "notes/lectures/лекция 14.10.md"
]
